# Generated by update-formula.sh for v0.3.0-alpha.13. Do not edit by hand.
class Rakitsu < Formula
  desc "Agent IDE for YAML-configured multi-agent systems (pre-release)"
  homepage "https://github.com/SK-ENT/rakitsu"
  version "0.3.0-alpha.13"
  license "BUSL-1.1"

  on_macos do
    on_arm do
      url "https://github.com/SK-ENT/rakitsu/releases/download/v0.3.0-alpha.13/rakitsu-darwin-arm64"
      sha256 "1435a924b1abbc4336738b9b7590e83c3fe247b323439dfb601679d05d9cf413"
    end
    on_intel do
      url "https://github.com/SK-ENT/rakitsu/releases/download/v0.3.0-alpha.13/rakitsu-darwin-amd64"
      sha256 "e8e3f41818c542287d6b9e70e97ffc730400582d72dd26abaefa34f68f8a98b4"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/SK-ENT/rakitsu/releases/download/v0.3.0-alpha.13/rakitsu-linux-arm64"
      sha256 "7ed6bc525068a58f2cf646b13e16caf3a03bf2a5f8bb517893d1655c1be2cece"
    end
    on_intel do
      url "https://github.com/SK-ENT/rakitsu/releases/download/v0.3.0-alpha.13/rakitsu-linux-amd64"
      sha256 "32885230e4fba9019e4c563faf717f335d732f8f858fcf3d7d8c0a9f402a4dc4"
    end
  end

  # BSL 1.1 requires the license to be conspicuously displayed on each copy.
  resource "license" do
    url "https://github.com/SK-ENT/rakitsu/releases/download/v0.3.0-alpha.13/LICENSE"
    sha256 "346c081942a62f6e19fca571ae1f5b5493463d1f04e3d15de4d2dd82cbdc998a"
  end

  resource "notice" do
    url "https://github.com/SK-ENT/rakitsu/releases/download/v0.3.0-alpha.13/NOTICE"
    sha256 "e343bcd150b2b378b09c558d30755eeb1f4070e4253db9c3eb7719b297971980"
  end

  def install
    bin.install Dir["rakitsu-*"].first => "rakitsu"
    resource("license").stage { prefix.install "LICENSE" }
    resource("notice").stage { prefix.install "NOTICE" }
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/rakitsu version")
  end
end
