# Generated by update-formula.sh for v0.3.0-alpha.12. Do not edit by hand.
class Rakitsu < Formula
  desc "Agent IDE for YAML-configured multi-agent systems (pre-release)"
  homepage "https://github.com/SK-ENT/rakitsu"
  version "0.3.0-alpha.12"
  license "BUSL-1.1"

  on_macos do
    on_arm do
      url "https://github.com/SK-ENT/rakitsu/releases/download/v0.3.0-alpha.12/rakitsu-darwin-arm64"
      sha256 "344537f16875b0874426f69d0594ce13bfd0c03cb440a522539a96c62800ff94"
    end
    on_intel do
      url "https://github.com/SK-ENT/rakitsu/releases/download/v0.3.0-alpha.12/rakitsu-darwin-amd64"
      sha256 "035b82db5e6aa95a089decd6af0293d5f7de1fc894b765f62d5960bc2c050d18"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/SK-ENT/rakitsu/releases/download/v0.3.0-alpha.12/rakitsu-linux-arm64"
      sha256 "40c20b3b87d602a3523d8063040492cea1c237dd779d76a3d33baeb7601f9b8b"
    end
    on_intel do
      url "https://github.com/SK-ENT/rakitsu/releases/download/v0.3.0-alpha.12/rakitsu-linux-amd64"
      sha256 "579115ea57a2947051809b920b04e92c5486911624b69921667427af57b5a5fb"
    end
  end

  # BSL 1.1 requires the license to be conspicuously displayed on each copy.
  resource "license" do
    url "https://github.com/SK-ENT/rakitsu/releases/download/v0.3.0-alpha.12/LICENSE"
    sha256 "346c081942a62f6e19fca571ae1f5b5493463d1f04e3d15de4d2dd82cbdc998a"
  end

  resource "notice" do
    url "https://github.com/SK-ENT/rakitsu/releases/download/v0.3.0-alpha.12/NOTICE"
    sha256 "e343bcd150b2b378b09c558d30755eeb1f4070e4253db9c3eb7719b297971980"
  end

  def install
    bin.install Dir["rakitsu-*"].first => "rakitsu"
    resource("license").stage { prefix.install "LICENSE" }
    resource("notice").stage { prefix.install "NOTICE" }
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/rakitsu version")
  end
end
