# Generated by update-formula.sh for v0.3.0-alpha.14. Do not edit by hand.
class Rakitsu < Formula
  desc "Agent IDE for YAML-configured multi-agent systems (pre-release)"
  homepage "https://github.com/SK-ENT/rakitsu"
  version "0.3.0-alpha.14"
  license "BUSL-1.1"

  on_macos do
    on_arm do
      url "https://github.com/SK-ENT/rakitsu/releases/download/v0.3.0-alpha.14/rakitsu-darwin-arm64"
      sha256 "65698c6048ea8adeb88f31636a76e4ad83c914477ea901a1a9c863509c63ef74"
    end
    on_intel do
      url "https://github.com/SK-ENT/rakitsu/releases/download/v0.3.0-alpha.14/rakitsu-darwin-amd64"
      sha256 "d6d4aba3d6859bbf417aab27d0845061bef137de75abc98064ca867bf57a3d00"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/SK-ENT/rakitsu/releases/download/v0.3.0-alpha.14/rakitsu-linux-arm64"
      sha256 "7c0e3d23b9d9c3466bfb14e521b42ffe26063fcf6e6926c723f54e11987cf0f0"
    end
    on_intel do
      url "https://github.com/SK-ENT/rakitsu/releases/download/v0.3.0-alpha.14/rakitsu-linux-amd64"
      sha256 "0ef3415184873c32a785991ac260cdbf743fc25a945365def9a7dacb5f9586e6"
    end
  end

  # BSL 1.1 requires the license to be conspicuously displayed on each copy.
  resource "license" do
    url "https://github.com/SK-ENT/rakitsu/releases/download/v0.3.0-alpha.14/LICENSE"
    sha256 "346c081942a62f6e19fca571ae1f5b5493463d1f04e3d15de4d2dd82cbdc998a"
  end

  resource "notice" do
    url "https://github.com/SK-ENT/rakitsu/releases/download/v0.3.0-alpha.14/NOTICE"
    sha256 "e343bcd150b2b378b09c558d30755eeb1f4070e4253db9c3eb7719b297971980"
  end

  def install
    bin.install Dir["rakitsu-*"].first => "rakitsu"
    resource("license").stage { prefix.install "LICENSE" }
    resource("notice").stage { prefix.install "NOTICE" }
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/rakitsu version")
  end
end
